### ISSUE TITLE
Mesh download issue

### ISSUE THREAD

**Issue by 3dproduction** [Sayduck/sayduck-platform-feedback#11]
Hi,
Whenever we are trying to download mesh from platform, in some mesh we are not able to download .obj file, Instead it open new tab and shows this as in image.

![image](https://user-images.githubusercontent.com/87762015/126980048-e31e2936-9357-444e-ba97-10a24095ca15.png)

Please help how we can execute this problem.

Thank you.

**Comment by ghost** [comment]
Hi, 

This is a shortcoming with the OBJ format. As OBJ format is a simple text format, in some cases, your browser will open the content of the file instead of triggering the download.

To save this file on your computer, you can click on `File > Save As`.

Let me know if further assistance is needed on this matter
