### ISSUE TITLE
Publish issue

### ISSUE THREAD

**Issue by 3dproduction** [Sayduck/sayduck-platform-feedback#5]
![image](https://user-images.githubusercontent.com/87762015/126485620-c86ef7b6-d890-42af-8eb8-0fb9a13c3ce2.png)
We have publishing error while we try to publish an product on Sayduck platform.
Here I have attached screenshot for reference what we are facing.
Please help us resolving this error.

Thank you.

**Comment by JoelSayduck** [comment]
Hi,

Thank you for this report.

Can you tell me the product name that you are having these issues with and we will look into it?

**Comment by 3dproduction** [comment]
Hi,
I am attaching product link here, Please tell us if it will work.
https://platform.sayduck.com/editor/UHJvZHVjdC1jOTBjMjAzMC1jYTc4LTAxMzktZTRkMy03NjljZTBmN2VkNjk=/information/properties

Thank you.

**Comment by 3dproduction** [comment]
And every product I am trying to publish,  I am facing this issue.

**Comment by JoelSayduck** [comment]
Hi, 

The issue was that an asset was taken for some texture even though they are supposed to be unique. We used the Clear all unused materials (https://help.sayduck.com/en/article/materials-and-textures-196o2nh/#5-remove-unused-materials) and textures and the product publishes now without any issues. 

We will try to clarify the error banner to be more clear. 

Let us know if this happens again.

**Comment by 3dproduction** [comment]
Yes thank you so much for this information,
We'll try this method, And if we'll stuck anywhere we'll let you know.

Thank you.
